### ISSUE TITLE
Integrate with unofficial Marketo PHP client library

### ISSUE THREAD

**Issue by mccrodp** [mccrodp/marketo_rest#4]
https://github.com/dchesterton/marketo-rest-api

**Comment by Jaesin** [comment]
I think this is a great idea. One thing to note is that it is built on guzzle 3 and drupal 8 now requires guzzle `^6.2.1`. See https://httpoxy.org/, https://github.com/dchesterton/marketo-rest-api/issues/33.

**Comment by mccrodp** [comment]
Hey @Jaesin. Yes, definitely a win-win situation where a D8 version is concerned. What about D7 though, any thoughts on where requiring guzzle for this is overkill there? 1st things 1st though, I will get all going as is for now, still a good few days / weeks work left before a dev release there. 

Are you looking at this in terms of future prospects for D8 only, or any use case for D7 at the moment?

For the proxy vulnerability, I have to look into it but you think it's best for me to remove the proxy support from the module (it was there from Marketo MA and I haven't tested it).

Thanks!

**Comment by Jaesin** [comment]
In D7 it's debatable since you might then need [composer_manager](https://www.drupal.org/project/composer_manager).

**Comment by mccrodp** [comment]
Yep, that's true as it is only deprecated on D8. Might be one for D8, will see :)

**Comment by Jaesin** [comment]
I added a `getFields` command and some tests to the rest API here: 

https://github.com/Jaesin/marketo-rest-api

**Comment by mccrodp** [comment]
That's great, will you create a PR on the origin of the fork or are you thinking otherwise? I saw there was one on the describe api, did you use that for `getFields()`? https://github.com/dchesterton/marketo-rest-api/issues/29

How is the D8 work going?

**Comment by Jaesin** [comment]
I didn't see the other pull requests at first. Now I see that this library hasn't been updated in 9 months. 

I might have to fork it and put it on packagist if he doesn't respond.

The D8 module is coming now that the API issues are sorted, there is a wrapper service for the API calls so it could use either library.

**Comment by mccrodp** [comment]
Sounds great, a new entry on packagist will be the way to go if you don't hear back, good idea.

**Comment by amjithps** [comment]
Errors on composer update : "Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

Another error Fatal error: Class 'CSD\Marketo\Client' not found

Not sure how this will work

**Comment by mccrodp** [comment]
Hi @amjithps - I believe you are referring to the Marketo Client repo by dchesterton or Jaesin above rather than this `marketo_rest` repo. Sounds like a good PR on the composer.json in those repos though! 😉

**Comment by amjithps** [comment]
@mccrodp  Hooo yes. sorry.  I just only found dchesterton class for custom applications which is full of bugs.

**Comment by mccrodp** [comment]
Hey, no worries, might be worth talking to Jaesin above about this and using his fork instead...the dchesterton repo is pretty old.

**Comment by amjithps** [comment]
Thank you. i will try.

**Comment by dhkmr2006** [comment]
Hi Guys, I am facing same issue while upgrading drupal 8.8.2 kindly let me know how to resolve this.

The website encountered an unexpected error. Please try again later.
Error: Class 'CSD\Marketo\Client' not found in Drupal\marketo_ma\Service\MarketoMaApiClient->getClient() (line 119 of modules/patched/marketo_ma/src/Service/MarketoMaApiClient.php).

Thanks in advance

**Comment by mccrodp** [comment]
Hey @dhkmr2006, this is the repo of an unmaintained fork. Please see Marketo MA on Drupal.org.
