### ISSUE TITLE
Munchkin API broken by Rest field names

### ISSUE THREAD

**Issue by neclimdul** [mccrodp/marketo_rest#6]
http://developers.marketo.com/documentation/websites/munchkin-api/

Things like associateLead that are used by the marketo_rest_webform module use the SOAP field names but rest calls through out the rest of the system require the REST field fields. Unfortunately these are different so storing the field names of one will break the functionality of the other so it seems like there needs to be a combined list or 2 separate lists.

Note: the describe rest API provides both names so pulling the 2 lists should be no problem.

**Comment by mccrodp** [comment]
Thanks a lot for this @neclimdul, obvious a crucial one here. I have been focusing on the REST side of things only so far, so this has obviously broken Munchkin to suit REST. So, the SOAP and Munchkin were the same then I'm guessing for certain fields. I imagine "Email" is one here, where it is "email" in REST, perhaps the "LeadSource" is another where it is "leadSource" in REST.

I'll have to take a look at the code closer to come up with a solution as I'm not sure all of the places that this comes into play. Any ideas / solutions / PRs welcome :)

**Comment by neclimdul** [comment]
Right, email worked fine but firstName and lastName failed since the SOAP values where FirstName and LastName so I ended up with an empty lead.

**Comment by mccrodp** [comment]
Ok, good to know. So you were using webform submodule and had munchkin set
as the API and this happened?
If I get steps to reproduce, perhaps I can work on this as early as
tomorrow. Thanks!

**Comment by neclimdul** [comment]
Exactly the case. Was testing the webform sub module and the site default tracking was munchkin.

**Comment by mccrodp** [comment]
@neclimdul - Just having a think about this looking at the DB, it seems we may have to introduce a new column in `marketo_rest_webform_component` table: `marketo_munchkin_key` and has you say, when using the `describe` API, pull back both the SOAP and the REST values and store in the respective columns: `marketo_rest_key` and the new `marketo_munchkin_key`, then we can maintain the field mappings on webform and allow the default API to be swapped seamlessly.

**EDIT**: The above is a table for existing / new component -> Marketo mappings, but we need a centralised place to retrieve the inactive API field name. i.e. - if we map to a REST field name, we need to store the Munchkin fieldname, so we need to get this from somewhere. (See following comment)

**Comment by mccrodp** [comment]
Some other areas I've notice now that need to be re-worked:

"Field definition" tab @ _admin/config/search/marketo_rest_ : when we "Retrieve from Marketo" we need to pull in and store both the REST and SOAP (Munchkin) field names. 

So, `prepareFields` needs to return the SOAP fieldname also:

``` php
private function prepareFields($result) {
    $result = $this->prepareResults($result);
    if (!empty($result['result'])) {
      $fields = array();
      foreach ($result['result'] as $field) {
        if (!empty($field['rest']['name'])) {
          $fields[$field['rest']['name']] = $field;
        }
      }
      return $fields;
    }
    return FALSE;
  }
```

Then store as a keyed array in the existing variable`marketo_rest_webform_fields` and update `MARKETO_REST_WEBFORM_FIELD_DEFAULTS` to also be an array.

Any suggestions are welcomed on approach before I start. Thanks 👍

**Comment by neclimdul** [comment]
Yeah I think we're thinking the same thing. I've been pondering something and its only half baked but its similar to what you where talking about in your previous comment.

Since the dataset of field data is getting more complicated (and for me is quite big) it seem that maybe the editable text field is outgrowing its usability. Its sort of large and error prone and with the addition of more data increasingly complicated. There is an important functionality is provides though, and that's the ability to remove fields from those visible and usable on the site.

Based on that, it might make sense to sync fields to a database table that has a column for local site "visibility" and the names id etc. Then syncing is just updating missing entries in the table. This provides improved ability to keep fields removed across syncs meaning they can be automated better and I've been told you can never delete fields in marketo so this would improve the ability to "remove" a field from effective use. It then makes REST/SOAP name resolution just a simple DB lookup.

**Comment by mccrodp** [comment]
^ This makes a lot of sense to me.

So, perhaps the clunky textfield can be removed, if we had something that was better suited to the task from a UI perspective. I was thinking something like checkboxes that defaulted to checked (Enabled). However, this would need to be in a scrolling panel, otherwise the page would be incredibly long; I'm not sure how that is for usability though?! Any ideas / alternatives? I don't like the textarea also, as it is `key|value` and our _key_ now changes depending on whether we are in REST or Munchkin API mode.

The above requires a new DB table then also, I'm thinking something like `marketo_rest_fields` as the fields are not necessarily specific to the webform submodule. It would have fields such as `marketo_rest_key` (Primary), `marketo_munchkin_key`, `enabled`. Any others?

I'll work on this in a PR when the plan is more solid. If I could tag you when it's ready for a review if that's ok, seeing as it's a significant change. Thanks.

**Comment by neclimdul** [comment]
I'd probably make the field management its own page(local task/tab)  as far as the ui, a giant page of checkboxes would be pretty consistent with other Drupal UIs and easy to implement. A prettier UI might be two columns Active/Inactive with some sort of method for moving between. Something like http://jqueryui.com/sortable/#connect-lists maybe. But I don't have a reference or pointers for implementing such a thing and it would require quite a bit more and an additional library/module in d7 to work so maybe just the checkboxes. :)

I might call the table `marketo_rest_lead_fields` only because its possible we might want to integrate fields from other objects in the future like companies. http://developers.marketo.com/documentation/company-api/describe-company/

For the columns, I'd do.

| Column | type | key |
| --- | :-: | --: |
| marketo_id | int | pk |
| marketo_rest_key | varchar |  |
| marketo_munchkin_key | varchar |  |
| enabled | int |  |

I don't think string keys would change in marketo but the ID surely won't and seems safer to sync on. Its also a bit more efficient a key in MySQL at least.

When you've got the WIP PR please do tag me. I'd be happy to provide feed back and testing on even the ugliest early implementations. Or even provide code if there's something I can help with. :)

**Comment by mccrodp** [comment]
All sounds great and I'll go with all of your suggestions, unless I come
across anything we are yet to identify that changes anything. Much
appreciated.

**Comment by mccrodp** [comment]
`marketo_rest_webform_component` will then have the `marketo_rest_key` changed to `marketo_id`

``` sql
CREATE TABLE `marketo_rest_webform_component` (
  `nid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The node identifier of a webform.',
  `cid` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'The identifier for this component within this node, starts at 0 for each node.',
  `marketo_id`  int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The Marketo identifier of a field.'
  PRIMARY KEY (`nid`,`cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Webform Component Settings';
```

**Comment by mccrodp** [comment]
Merged.
